name: ci-cd

on:
  push:
    branches:
      - "master"

jobs:
  ci-cd-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/47_billion:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/47_billion:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/47_billion:buildcache,mode=max
      - name: Run
        run: docker run -d --name mycontainer -p 7000:7000 lagnesh712/47_billion
      - name: docker ps
        run: docker ps 
      - name: docker logs
        run: |
          docker logs mycontainer
          sleep 30
          docker ps 
      - name: installing pytest
        run: pip install pytest
      - name: api testing
        run: python3 api_test.py
      - name: minikube testing
        run: minikube start
      - name: deploying on cluster
        run: sh kubectl.sh
      - name: put pods on wait
        run: sleep 30
      - name: checking sccessfull deployment
        run: kubectl get all



